/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import JoyStick from "./script/JoyStick"
import JoyStickButton from "./script/JoyStickButton"
import AdjustScene from "./script/AdjustScene"
import GameJoyStick from "./script/GameJoyStick"
import Camera from "./script/Camera"
import LevelLogic from "./script/LevelLogic"
import BrickLogic from "./script/BrickLogic"
import AILeftOrRight from "./script/AILeftOrRight"
import GroundImageLogic from "./script/GroundImageLogic"
import GameUI from "./script/GameUI"
import GameControl from "./script/GameControl"
import BrokenBrick from "./script/BrokenBrick"
import Bullet from "./script/Bullet"
import DropBox from "./script/DropBox"
import Role from "./script/Role"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/JoyStick.js",JoyStick);
		reg("script/JoyStickButton.js",JoyStickButton);
		reg("script/AdjustScene.js",AdjustScene);
		reg("script/GameJoyStick.js",GameJoyStick);
		reg("script/Camera.js",Camera);
		reg("script/LevelLogic.js",LevelLogic);
		reg("script/BrickLogic.js",BrickLogic);
		reg("script/AILeftOrRight.js",AILeftOrRight);
		reg("script/GroundImageLogic.js",GroundImageLogic);
		reg("script/GameUI.js",GameUI);
		reg("script/GameControl.js",GameControl);
		reg("script/BrokenBrick.js",BrokenBrick);
		reg("script/Bullet.js",Bullet);
		reg("script/DropBox.js",DropBox);
		reg("script/Role.js",Role);
    }
}
GameConfig.width = 1336;
GameConfig.height = 750;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "scene/Level1.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
